In [4]:
x1=[100] 
x2=[100]
print(id(x1))
print(id(x2))


2052599364352
2052599363392


In [11]:
a=([[1,2,3]
      ,[4,5,6],
      [7,8,9]])
print(a.transpose())

AttributeError: 'list' object has no attribute 'transpose'

In [17]:
import numpy as np
x1=2052599364352
x2=2052599363392
print(x1)
print(x2)
np.vstack((x1,x2))


2052599364352
2052599363392


array([[2052599364352],
       [2052599363392]], dtype=int64)

In [18]:
x1=2052599364352
x2=2052599363392
print(x1)
print(x2)
np.hstack((x1,x2))

2052599364352
2052599363392


array([2052599364352, 2052599363392], dtype=int64)

In [19]:
x3=[1,2,3,4,5,6,7,8]
x4=[2,4,6,8,2,4,6,8]
np.insert(x3,4,x4)

array([1, 2, 3, 4, 2, 4, 6, 8, 2, 4, 6, 8, 5, 6, 7, 8])

In [20]:
x5=[1,2,3,4,5,6,7,8]
x6=[100]
np.insert(x5,4,x6)

array([  1,   2,   3,   4, 100,   5,   6,   7,   8])

In [21]:
x3=[1,2,3,4,5,6,7,8]
x4=[2,4,6,8,2,4,6,8]
np.delete(x3,1)

array([1, 3, 4, 5, 6, 7, 8])