In [5]:
print("hi")

hi


In [3]:
a=10
b=20
c=a+b
c

30

In [6]:
!pip install numpy

In [7]:
import numpy as np
a=np.array([1,2,3,4,'a'])
a

array(['1', '2', '3', '4', 'a'], dtype='<U11')

In [10]:
a=np.array(10)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
print("a dimension:",a.ndim)
print("b dimension:",b.ndim)
print("c dimension:",c.ndim)
print("shape of a : ", a.shape)
print("shape of b : ", b.shape)
print("shape of c : ", c.shape)

a dimension: 0
b dimension: 1
c dimension: 2
shape of a :  ()
shape of b :  (3,)
shape of c :  (2, 3)


In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
np.eye(6,dtype=float)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [17]:
np.ones(3,2)

TypeError: Cannot interpret '2' as a data type

In [18]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.full((3,2),10,dtype=int)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [20]:
x=[1,2,3,4,5,6]
np.diag(x)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [25]:
x=np.arange(1,17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [27]:
x=np.arange(1,17)
n=x.reshape((8,2))
print(n)
print(n.shape)
print(n.ndim)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)
2


In [28]:
n1=x.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [29]:
v=n.ravel()
print(v)
print(v.shape)
print(v.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [30]:
n1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [32]:
b=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[7,8,9]]])
b.shape
b

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [7, 8, 9]]])

In [34]:
b[0][1][2]

6

In [35]:
b[0][1][1]

5

In [36]:
b[0][1]

array([4, 5, 6])

In [43]:
x1=[1, 2, 3, 4, 5]
x2=[1, 2, 3, 4, 5]
print(x1)
print(x2)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [44]:
print(id(x1))
print(id(x2))

2570078935488
2570078656832


In [45]:
print(np.shares_memory(x1,x2))

False
